#basic options
title: your awesome title
author: github user
email: morbidcorvidproductions@gmail.com
description: a wonderful site
twitter username: cursedcorvid
github username: morbidcorvidproductions

#Build settings
markdown: kramdown
theme: minima
