# basic options
title: your awesome title
author: github user
email: morbidcorvidproductions@gmail.com
description: a wonderful site
twitter: cursedcorvid
github: morbidcorvidproductions

#Build settings
markdown: kramdown
theme: naringu
