#basic options
title: your awesome title
author: github user
email: morbidcorvidproductions@gmail.com
description: a wonderful site
twitter_username: cursedcorvid
github_username: morbidcorvidproductions

#Build settings
markdown: kramdown
theme: minima
